language: java

dist: trusty

jdk:
  - oraclejdk8

# Init xvfb for headless GUI testing on trusty
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

# Auto tag commit with latest
before_deploy:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git tag -f latest
  - git remote set-url --push origin "https://${GH_TOKEN}@github.com/zetool/common.git"
  - git push --delete origin latest
  - git push --tags

# Disabled deployments to GitHub:
#deploy:
#  provider: releases
#  api_key:
#    secure: VFA7eszknbHWueXWlWhctLOcnsW9bU98bt8Jw5t6XjWcEzlj7oCGYmSC5nn5fsvqzUEoJZukPi6vvy0ZPTDPyP7L0zBesa46LC4HKqJVyB67SHGZi1HjlXVKXbg2nfoHV62xRIjwAMTXiZqWhwyoycyqgH67ytK6s5llUKokXWE6HoPm7PUHzNRdxkI0HDzUbn6DkexArDQP0YqJ6seouxgnRVm/ayMnFvDZmwNHA8mJOQaDCLNbjc9yEKPvldeAita5eKejjdqN7R16cCCy0Ae1fxMgBISqkSGNa19LpumSUIq7Zg8xYElQBItjvtXzh/xGkvwFvgehaW5O0CjuTyrGk0+jraHQMgcozi93+M6RAwQeWzNDBGnECTyT2D8GtgXH/y/wVljrsJ2mE6nUOwH4oJdN3J5fVERmTMnCPphIzwq30JXbOn+BZuf2mchQNU/RJv6y/uBz0mbcJBJLH1aTQmy2zyjrhQda7bWDVps9qoH8vEzC9PW8JETR1YJvz4iiKs6G+Lu3pGDYd7EO93nInceiPwT2paY8+8yYhUWXUN0JreJwEneyf/yIQv8o0NTZCKznkv1sdN3L2k1LSg1zhkonwsy9YZP/wlgN9g7pAWrpUshOjECvjjtsTTveHF+RI1h9MVA+yxdMEmowrfrV5hRyHabKrnKtgLM2Gmc=
#  file: target/common-0.1.0-SNAPSHOT.jar
#  skip_cleanup: true
#  overwrite: true
#  on:
#    branches:
#      only:
#        - master
#deploy:
#  provider: script
#  script: "mvn deploy -Dregistry=https://maven.pkg.github.com/zetool -Dtoken=${GH_TOKEN}"
#  skip_cleanup: true
#  on:
#    branches:
#      only:
#        - master

after_success:
  - bash <(curl -s https://codecov.io/bash)
