language: java

dist: trusty

jdk:
  - oraclejdk8

# Init xvfb for headless GUI testing on trusty
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

env:
  global:
    secure: s0CM8tOxmbCcptJft79y8zAv0giH7SaFDAuT6RuCoiOHOrJ3NFLp2Hk71X9x71ssDdI9tr/GwvWW035mC7dtWfDGUyALjSU6anhigg8fG4N72P5ps1SB+vKpIdqrHERaY6jElMpNPeudytm8aO+XA1WTYiHWpOYD1kcKOUAYcv8pSS5RRHQy9E25aqIOh/VusQFPsl7pnVVH2U/Pq2d8YXIxIFiEZWwSYQCdZmbXTTF9iT271lqolU5h3SBeg1vCheDpUGR220UF8w3rrIslcJomVlWyI8nONbB6JE73qrSJldC67yMRYkAiB4rK6t8K0lnwLHAjwEDugk0Ax3CdU9gnGyhTx2u+xusiT3ezCBONyx2XKJv6p7ppgQI7G5Z6NNPczLPM5z9fnrBOISO/docZKgFc456aVF/WR3HWa6GymGjHojBN0nxLiTuVRcDZkZKxxgJBFBXYb5QioxwcsG9ILTx+QtlMPu+MAYme6LaOgUDlKEMNUByVe6RBtJoLf8vXbioZWeKg3FpQ2hJOlK63HgIr4zORqA+4d/MeE396YFwH+4r80k90yxBEurE6uFZX9GcTDTOx4764GeaC7X4qokEWz565GNOXxFQOtO7O/Z4WvzFC3+oEUf8KBWxzxjaw3AT9k7K21m0xfxivGGhldPbJojjaS03xUWhhFOA=

# Auto tag commit with latest
before_deploy:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git tag -f latest
  #- git push --tags
  
deploy:
  provider: releases
  api_key:
    secure: s0CM8tOxmbCcptJft79y8zAv0giH7SaFDAuT6RuCoiOHOrJ3NFLp2Hk71X9x71ssDdI9tr/GwvWW035mC7dtWfDGUyALjSU6anhigg8fG4N72P5ps1SB+vKpIdqrHERaY6jElMpNPeudytm8aO+XA1WTYiHWpOYD1kcKOUAYcv8pSS5RRHQy9E25aqIOh/VusQFPsl7pnVVH2U/Pq2d8YXIxIFiEZWwSYQCdZmbXTTF9iT271lqolU5h3SBeg1vCheDpUGR220UF8w3rrIslcJomVlWyI8nONbB6JE73qrSJldC67yMRYkAiB4rK6t8K0lnwLHAjwEDugk0Ax3CdU9gnGyhTx2u+xusiT3ezCBONyx2XKJv6p7ppgQI7G5Z6NNPczLPM5z9fnrBOISO/docZKgFc456aVF/WR3HWa6GymGjHojBN0nxLiTuVRcDZkZKxxgJBFBXYb5QioxwcsG9ILTx+QtlMPu+MAYme6LaOgUDlKEMNUByVe6RBtJoLf8vXbioZWeKg3FpQ2hJOlK63HgIr4zORqA+4d/MeE396YFwH+4r80k90yxBEurE6uFZX9GcTDTOx4764GeaC7X4qokEWz565GNOXxFQOtO7O/Z4WvzFC3+oEUf8KBWxzxjaw3AT9k7K21m0xfxivGGhldPbJojjaS03xUWhhFOA=
  file: target/common-0.1.0-SNAPSHOT.jar
  skip_cleanup: true
  on:
    all_branches: true
    #branches:
    #  only:
    #    - latest
