# This workflow will release and publish the project with Maven
# It uses Maven release to release the process including deploy.
# Deployment is done to GitHub Package registry.

name: Maven Release

on:
  pull_request:
    branches:
    - master
    types: [closed]

jobs:
  release:
    name: Maven Release
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_RELEASE_TOKEN }}

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests
    - name: Prepare settings
      run: |
        mkdir -p ~/.m2
        echo "<settings><servers><server><id>github</id><username>zetool-bot</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
    - name: Release
      uses: qcastel/github-actions-maven-release@master
      with:
        release-branch-name: "master"

        maven-repo-server-id: github
        maven-repo-server-username: zetool-bot
        maven-repo-server-password: ${{ secrets.GITHUB_RELEASE_TOKEN }}

        maven-args: "-X -Dmaven.javadoc.skip=true -DskipTests"

        git-release-bot-name: "zetool-bot"
        git-release-bot-email: "github@zetool.org"

        access-token: ${{ secrets.GITHUB_RELEASE_TOKEN }}

